# Generated by Django 4.2.3 on 2023-08-07 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atomic_habits', '0003_alter_habit_time_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='обозначение привычки как уведомленную, чтобы избежать повторных уведомлений'),
        ),
        migrations.AddField(
            model_name='habit',
            name='notification_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время уведомления'),
        ),
        migrations.AddField(
            model_name='habit',
            name='telegram_chat_id',
            field=models.CharField(default=1, max_length=100, verbose_name='chat_id пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
